<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="moying_mcr">

  <xacro:arg name="mode" default="gazebo"/> 
  <xacro:arg name="settings" default=""/> 
  <xacro:property name="select_mode" value="$(arg mode)"/>
  <xacro:property name="select_settings" value="$(arg settings)"/>
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:include filename="$(find moying_mcr_description)/ros2_control/moying_mcr.ros2_control.xacro"/>
  <!-- ros2_control -->
  <xacro:moying_mcr_control mode="${select_mode}"/>

  <xacro:include filename="$(find moying_mcr_description)/urdf/body.urdf.xacro"/>

  <material name="DarkGrey"><color rgba="0.3 0.3 0.3 1.0"/></material>
  <material name="Silver"><color rgba="0.75 0.75 0.75 1.0"/></material>
  <material name="BrightWhite"><color rgba="0.8 0.8 0.8 1.0"/></material>
  <material name="GlassWhite"><color rgba="1 1 1 1.0"/></material>
  <material name="Pink"><color rgba="1 0.3 0.3 1.0"/></material>
  <material name="Robotiq-Black"><color rgba="0.2 0.2 0.2 1.0"/></material>
  <material name="Robotiq-Grey"><color rgba="0.4 0.4 0.4 1.0"/></material>

  <xacro:property name="wheel_radius" value="0.07625"/>
  <xacro:property name="roller_radius" value="0.009"/>

  <xacro:macro name="roller" params="prefix suffix theta">
    <xacro:property name="sqrt_2_2" value="${sqrt(2)/2}"/>
    <xacro:property name="roller_joint_axis_x" value="${cos(theta) * sqrt_2_2}"/>
    <xacro:property name="roller_joint_axis_y" value="${-reflect * sqrt_2_2}"/>
    <xacro:property name="roller_joint_axis_z" value="${sin(theta) * sqrt_2_2}"/>
    <xacro:property name="quat_x" value="${0}"/>
    <xacro:property name="quat_y" value="${roller_joint_axis_z}"/>
    <xacro:property name="quat_z" value="${-roller_joint_axis_y}"/>
    <xacro:property name="quat_w" value="${-(1+roller_joint_axis_x)}"/>
    <xacro:property name="quat_length" value="${sqrt(quat_y*quat_y + quat_z * quat_z+quat_w * quat_w)}"/>
    <xacro:property name="quat_normal_x" value="${0}"/>
    <xacro:property name="quat_normal_y" value="${quat_y/quat_length}"/>
    <xacro:property name="quat_normal_z" value="${quat_z/quat_length}"/>
    <xacro:property name="quat_normal_w" value="${quat_w/quat_length}"/>
    <link name="${prefix}_roller_${suffix}">
      <collision>
        <origin rpy="${atan2(2. * (quat_normal_w * quat_normal_x + quat_normal_y * quat_normal_z), 1. - 2. * (quat_normal_x * quat_normal_x + quat_normal_y * quat_normal_y))} ${asin(2. * (quat_normal_w * quat_normal_y - quat_normal_z * quat_normal_x))} ${atan2(2. * (quat_normal_w * quat_normal_z + quat_normal_x * quat_normal_y), 1. - 2. * (quat_normal_y * quat_normal_y + quat_normal_z * quat_normal_z))}" xyz="0 0 0"/>
        <geometry><mesh filename="package://moying_mcr_description/meshes/chassis/roller.stl" scale="0.0019 0.0019 0.0019"/></geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="2.036"/>
        <inertia ixx="3128e-9" ixy="0.0" ixz="0.0" iyy="3128e-9" iyz="0.0" izz="3128e-9"/>
      </inertial>
    </link>
    <joint name="${prefix}_roller_${suffix}_joint" type="continuous">
        <origin xyz="${(wheel_radius-roller_radius)*cos(theta-pi/2)} 0 ${(wheel_radius-roller_radius)*sin(theta-pi/2)}" rpy="0 0 0"/>
        <axis xyz="${roller_joint_axis_x} ${roller_joint_axis_y} ${roller_joint_axis_z}"/>
        <dynamics damping="0.0" friction="0.001"/>
        <parent link="${prefix}_wheel"/>
        <child link="${prefix}_roller_${suffix}"/>
    </joint>
    <gazebo reference="${prefix}_roller_${suffix}">
        <mu1 value="2000.0"/><mu2 value="2000.0"/>
        <kp value="1000000.0"/><kd value="100.0"/>
        <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="mecanum_wheel" params="prefix connected_to wheel_x_offset wheel_y_offset wheel_z_offset wheel_rpyr_offset wheel_rpyp_offset wheel_rpyy_offset reflect max_effort max_velocity">
    <link name="${prefix}_wheel">
      <visual>
        <xacro:if value="${reflect == 1}"><origin xyz="0 -0.048 0" rpy="1.57 0 0" /></xacro:if>
        <xacro:if value="${reflect == -1}"><origin xyz="0 0.048 0" rpy="1.57 0 0" /></xacro:if>
        <geometry>
          <xacro:if value="${reflect == 1}"><mesh filename="package://moying_mcr_description/meshes/chassis/left_wheel.STL" scale="1000 1000 1000"/></xacro:if>
          <xacro:if value="${reflect == -1}"><mesh filename="package://moying_mcr_description/meshes/chassis/right_wheel.STL" scale="1000 1000 1000"/></xacro:if>
        </geometry>
      </visual>
      <collision>
        <xacro:if value="${reflect == 1}"><origin xyz="0 0.0 0" rpy="1.57 0 0" /></xacro:if>
        <xacro:if value="${reflect == -1}"><origin xyz="0 0.0 0" rpy="1.57 0 0" /></xacro:if>
        <geometry><cylinder length="0.09" radius="0.088"/></geometry>
      </collision>
      <inertial>
        <mass value="10.59"/>
        <inertia ixx="1.416e-3" ixy="0.0" ixz="0.0" iyy="2.749e-3" iyz="0.0" izz="1.416e-3"/>
      </inertial>
    </link>
    <joint name="${prefix}_wheel_joint" type="revolute">
      <axis xyz="0 1 0"/>
      <origin xyz="${wheel_x_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="${wheel_rpyr_offset} ${wheel_rpyp_offset} ${wheel_rpyy_offset}"/>
      <limit effort="${max_effort}" velocity="${max_velocity}" lower="-1e9" upper="1e9"/>
      <dynamics damping="0.0" friction="0.05"/>
      <parent link="${connected_to}"/>
      <child link="${prefix}_wheel"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="omni_wheel" params="prefix connected_to wheel_x_offset wheel_y_offset wheel_z_offset wheel_rpyr_offset wheel_rpyp_offset wheel_rpyy_offset reflect max_effort max_velocity">
    <link name="${prefix}_pivot_link">
      <visual>
        <xacro:if value="${reflect == 1}"><origin xyz="0 -0.048 0" rpy="1.57 0 0" /></xacro:if>
        <xacro:if value="${reflect == -1}"><origin xyz="0 0.048 0" rpy="1.57 0 0" /></xacro:if>
        <geometry><cylinder radius="0.01" length="0.05"/></geometry>
      </visual>
      <inertial>
        <mass value="1.59"/>
        <inertia ixx="1.416e-3" ixy="0.0" ixz="0.0" iyy="2.749e-3" iyz="0.0" izz="1.416e-3"/>
      </inertial>
    </link>
    <joint name="${prefix}_pivot_joint" type="revolute">
      <axis xyz="0 0 1"/>
      <origin xyz="${wheel_x_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="${wheel_rpyr_offset} ${wheel_rpyp_offset} ${wheel_rpyy_offset}"/>
      <limit effort="${max_effort}" velocity="${max_velocity}" lower="-1e9" upper="1e9"/>
      <dynamics damping="0.0" friction="0.05"/>
      <parent link="${connected_to}"/>
      <child link="${prefix}_pivot_link"/>
    </joint>
    <link name="${prefix}_drive_link">
      <visual><geometry><cylinder radius="0.1" length="0.1"/></geometry></visual>
      <collision><geometry><cylinder radius="0.1" length="0.1"/></geometry></collision>
      <inertial>
        <mass value="1.59"/>
        <inertia ixx="1.416e-3" ixy="0.0" ixz="0.0" iyy="2.749e-3" iyz="0.0" izz="1.416e-3"/>
      </inertial>
    </link>
    <joint name="${prefix}_drive_joint" type="revolute">
      <axis xyz="0 0 -1"/>
      <origin xyz="0 0 0 " rpy="1.571 0 0"/>
      <limit effort="${max_effort}" velocity="${max_velocity}" lower="-1e9" upper="1e9"/>
      <dynamics damping="0.0" friction="0.05"/>
      <parent link="${prefix}_pivot_link"/>
      <child link="${prefix}_drive_link"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="moying_chassis_description" params="mode">
    <xacro:macro name="cuboid_inertia_def" params="width height length mass">
      <xacro:property name="mass1" value="${mass}"/>
      <xacro:property name="width1" value="${width}"/>
      <xacro:property name="length1" value="${length}"/>
      <xacro:property name="height1" value="${height}"/>
      <inertia ixx="${mass1 * (height1 * height1 + length1 * length1) / 12}" iyy="${mass1 * (width1 * width1 + height1 * height1) / 12}" izz="${mass1 * (width1 * width1 + length1 * length1) / 12}" ixy="0" iyz="0" ixz="0"/>
    </xacro:macro>

    <joint name="vehicle_body_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0.03"/>
      <parent link="base_link"/>
      <child link="vehicle_body"/>
    </joint>
    <link name="vehicle_body">
      <inertial>
        <mass value="100"/>
        <origin rpy="0 0 0" xyz="0 0 -0.03 "/>
        <xacro:cuboid_inertia_def mass="100" length="1.002" height="0.1" width="0.622"/>
      </inertial>
      <visual>
        <origin rpy="1.5707963267948966 0 1.5707963267948966" xyz="0 0 -0.03 "/>
        <geometry><mesh filename="package://moying_mcr_description/meshes/chassis/MQ60.STL" scale="0.001 0.001 0.001"/></geometry>
        <material name="Silver"/>
      </visual>
      <xacro:if value="${mode == 'real'}">
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0.387"/>
          <geometry><box size="0.6 0.4 0.234"/></geometry>
        </collision>
      </xacro:if>
    </link>

    <xacro:if value="${mode == 'real'}">
      <xacro:mecanum_wheel prefix="forward_left" connected_to="base_link" wheel_x_offset="0.27" wheel_y_offset="0.1795" wheel_z_offset="0.088" wheel_rpyr_offset="0" wheel_rpyp_offset="0" wheel_rpyy_offset="0" reflect="1" max_effort="5" max_velocity="50"/>
      <xacro:mecanum_wheel prefix="forward_right" connected_to="base_link" wheel_x_offset="0.27" wheel_y_offset="-0.1795" wheel_z_offset="0.088" wheel_rpyr_offset="0" wheel_rpyp_offset="0" wheel_rpyy_offset="0" reflect="-1" max_effort="5" max_velocity="50"/>
      <xacro:mecanum_wheel prefix="back_left" connected_to="base_link" wheel_x_offset="-0.27" wheel_y_offset="0.1795" wheel_z_offset="0.088" wheel_rpyr_offset="0" wheel_rpyp_offset="0" wheel_rpyy_offset="0" reflect="-1" max_effort="5" max_velocity="50"/>
      <xacro:mecanum_wheel prefix="back_right" connected_to="base_link" wheel_x_offset="-0.27" wheel_y_offset="-0.1795" wheel_z_offset="0.088" wheel_rpyr_offset="0" wheel_rpyp_offset="0" wheel_rpyy_offset="0" reflect="1" max_effort="5" max_velocity="50"/>
    </xacro:if>
    <xacro:if value="${mode == 'gazebo'}">
      <xacro:omni_wheel prefix="forward_left" connected_to="base_link" wheel_x_offset="0.27" wheel_y_offset="0.1795" wheel_z_offset="0.088" wheel_rpyr_offset="0" wheel_rpyp_offset="0" wheel_rpyy_offset="0" reflect="1" max_effort="5" max_velocity="50"/>
      <xacro:omni_wheel prefix="forward_right" connected_to="base_link" wheel_x_offset="0.27" wheel_y_offset="-0.1795" wheel_z_offset="0.088" wheel_rpyr_offset="0" wheel_rpyp_offset="0" wheel_rpyy_offset="0" reflect="-1" max_effort="5" max_velocity="50"/>
      <xacro:omni_wheel prefix="back_left" connected_to="base_link" wheel_x_offset="-0.27" wheel_y_offset="0.1795" wheel_z_offset="0.088" wheel_rpyr_offset="0" wheel_rpyp_offset="0" wheel_rpyy_offset="0" reflect="-1" max_effort="5" max_velocity="50"/>
      <xacro:omni_wheel prefix="back_right" connected_to="base_link" wheel_x_offset="-0.27" wheel_y_offset="-0.1795" wheel_z_offset="0.088" wheel_rpyr_offset="0" wheel_rpyp_offset="0" wheel_rpyy_offset="0" reflect="1" max_effort="5" max_velocity="50"/>
    </xacro:if>
  </xacro:macro>

  <xacro:property name="density" value="3.09"/>
  <xacro:macro name="elfin3_description" params="prefix parent r p y">
    <joint name="${prefix}_world_base" type="fixed">
      <origin xyz= "0 0 0" rpy="${r} ${p} ${y}" />
      <parent link="${parent}" />
      <child link="${prefix}_elfin_base_link" />
    </joint>
    <link name="${prefix}_elfin_base_link"/>
    <joint name="${prefix}_elfin_base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 ${PI/2}" />
      <parent link="${prefix}_elfin_base_link" />
      <child link="${prefix}_elfin_base" />
    </joint>

    <link name="${prefix}_elfin_base">
      <inertial>
        <origin xyz="0.000476057496448 -0.00609847721085 0.0271227961552" rpy="0 0 0"/>
        <mass value="${0.432503561632*density}"/>
        <inertia ixx="${0.00107966*density}" ixy="${6.43e-06*density}" ixz="${1.97e-06*density}" iyy="${0.00089216*density}" iyz="${-1.269e-05*density}" izz="${0.00174712*density}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_base.STL" /></geometry>
        <material name="metal_white"/>
      </visual>
    </link>
    <link name="${prefix}_elfin_link1">
      <inertial>
        <origin xyz="-0.0192425632808 0.120157543892 -2.05350524914e-05" rpy="0 0 0"/>
        <mass value="${1.52001312557*density}"/>
        <inertia ixx="${0.00523815*density}" ixy="${0.00122593*density}" ixz="${-1.6e-07*density}" iyy="${0.00315471*density}" iyz="${-6.4e-07*density}" izz="${0.00646649*density}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_link1.STL" /></geometry>
        <material name="metal"/>
      </visual>
    </link>
    <joint name="${prefix}_elfin_joint1" type="revolute">
      <origin xyz="0 0 0.031" rpy="${PI/2} 0 0" />
      <parent link="${prefix}_elfin_base" />
      <child link="${prefix}_elfin_link1" />
      <axis xyz="0 1 0" />
      <limit lower="-3.14" upper="3.14" effort="104" velocity="1.57" />
    </joint>
    <link name="${prefix}_elfin_link2">
      <inertial>
        <origin xyz="-0.0363359816546 0.121774838175 -3.84046105722e-05" rpy="0 0 0"/>
        <mass value="${0.519672255247*density}"/>
        <inertia ixx="${0.00564813*density}" ixy="${-0.00026473*density}" ixz="${0.0*density}" iyy="${0.00053594*density}" iyz="${1.29e-06*density}" izz="${0.00545618*density}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_link2.STL" /></geometry>
        <material name="metal_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0.12 0" rpy="1.57 0 0" />
        <geometry><cylinder length="0.32" radius="0.05"/></geometry>
      </collision>
    </link>
    <joint name="${prefix}_elfin_joint2" type="revolute">
      <origin xyz="-0.068808 0.1615 0" rpy="0 0 0" />
      <parent link="${prefix}_elfin_link1" />
      <child link="${prefix}_elfin_link2" />
      <axis xyz="-1 0 0" />
      <limit lower="-3.14" upper="3.14" effort="104" velocity="1.57" />
    </joint>
    <link name="${prefix}_elfin_link3">
      <inertial>
        <origin xyz="0.0513625008301 -0.0377418700977 -1.41484011876e-05" rpy="0 0 0"/>
        <mass value="${1.07514585114*density}"/>
        <inertia ixx="${0.00296619*density}" ixy="${0.00072021*density}" ixz="${7.3e-07*density}" iyy="${0.00182263*density}" iyz="${-3.7e-07*density}" izz="${0.00372855*density}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_link3.STL" /></geometry>
        <material name="metal"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_link3.STL" /></geometry>
      </collision>
    </link>
    <joint name="${prefix}_elfin_joint3" type="revolute">
      <origin xyz="0 0.266 0" rpy="${-PI} 0 0" />
      <parent link="${prefix}_elfin_link2" />
      <child link="${prefix}_elfin_link3" />
      <axis xyz="1 0 0" />
      <limit lower="-3.14" upper="3.14" effort="69" velocity="1.57" />
    </joint>
    <link name="${prefix}_elfin_link4">
      <inertial>
        <origin xyz="-0.0580853772834 0.10002233137 -3.45203877103e-06" rpy="0 0 0"/>
        <mass value="${0.37026646381*density}"/>
        <inertia ixx="${0.00238279*density}" ixy="${0.00082955*density}" ixz="${1.1e-07*density}" iyy="${0.00095758*density}" iyz="${-3.2e-07*density}" izz="${0.00285161*density}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_link4.STL" /></geometry>
        <material name="metal_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.57 0 0" />
        <geometry><cylinder length="0.15" radius="0.05"/></geometry>
      </collision>
    </link>
    <joint name="${prefix}_elfin_joint4" type="revolute">
      <origin xyz="0.068808 -0.10523 0" rpy="${PI} 0 0" />
      <parent link="${prefix}_elfin_link3" />
      <child link="${prefix}_elfin_link4" />
      <axis xyz="0 1 0" />
      <limit lower="-3.14" upper="3.14" effort="69" velocity="1.57" />
    </joint>
    <link name="${prefix}_elfin_link5">
      <inertial>
        <origin xyz="-0.0158710385319 -0.0365214098995 4.94388107361e-07" rpy="0 0 0"/>
        <mass value="${0.807027243448*density}"/>
        <inertia ixx="${0.00193719*density}" ixy="${0.00047145*density}" ixz="${2e-08*density}" iyy="${0.00112857*density}" iyz="${-1.1e-07*density}" izz="${0.00245655*density}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_link5.STL" /></geometry>
        <material name="metal"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_link5.STL" /></geometry>
      </collision>
    </link>
    <joint name="${prefix}_elfin_joint5" type="revolute">
      <origin xyz="0 0.21877 0" rpy="${-PI} 0 0" />
      <parent link="${prefix}_elfin_link4" />
      <child link="${prefix}_elfin_link5" />
      <axis xyz="1 0 0" />
      <limit lower="-3.14" upper="3.14" effort="34" velocity="1.57" />
    </joint>
    <link name="${prefix}_elfin_link6">
      <inertial>
        <origin xyz="-0.0009237 -0.042691 -0.0003367" rpy="0 0 0" />
        <mass value="${0.147312*density}"/>
        <inertia ixx="${0.00019407*density}" ixy="${1.4e-06*density}" ixz="${-2.89e-06*density}" iyy="${0.00019592*density}" iyz="${5e-08*density}" izz="${0.00019496*density}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry><mesh filename="package://moying_mcr_description/meshes/arm_elfin3/elfin_link6.STL" /></geometry>
        <material name="metal_white"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.57 0 0" />
        <geometry><cylinder length="0.2" radius="0.04"/></geometry>
      </collision>
    </link>
    <joint name="${prefix}_elfin_joint6" type="revolute">
      <origin xyz="0 -0.1065 0" rpy="${-PI} 0 ${-PI}" />
      <parent link="${prefix}_elfin_link5" />
      <child link="${prefix}_elfin_link6" />
      <axis xyz="0 -1 0" />
      <limit lower="-3.14" upper="3.14" effort="34" velocity="1.57" />
    </joint>
    <link name="${prefix}_elfin_end_link"/>
    <joint name="${prefix}_elfin_end_joint" type="fixed">
      <origin xyz="0 -0.19 0" rpy="${PI/2} ${-PI} 0" />
      <parent link="${prefix}_elfin_link6" />
      <child link="${prefix}_elfin_end_link" />
    </joint>
    <link name="${prefix}_elfin_dummy_gripper"/>
    <joint name="${prefix}_elfin_dummy_joint" type="fixed">
      <origin xyz="0 -0.111 0" rpy="${PI/2} ${-PI/2} 0" />
      <parent link="${prefix}_elfin_link6" />
      <child link="${prefix}_elfin_dummy_gripper" />
    </joint>
  </xacro:macro>

  <xacro:macro name="robotiq_ft300" params="parent tf_prefix *origin">
    <joint name="${tf_prefix}ft300_fix" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}" />
        <child link="${tf_prefix}ft300_mounting_plate" />
    </joint>
    <link name="${tf_prefix}ft300_sensor">
        <inertial>
            <origin xyz="0 0 ${-17 / 1000}" rpy="0 0 0"/>
            <mass value="0.300"/>
            <inertia ixx="${262 / 1000000}" ixy="0" ixz="${1 / 1000000}" iyy="${265 / 1000000}" iyx="0" iyz="${1 / 1000000}" izz="${219 / 1000000}" izx="${-1 / 1000000}" izy="${1 / 1000000}"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry><mesh filename="package://moying_mcr_description/meshes/sensor/visual/robotiq_ft300.STL"/></geometry>
            <material name="Robotiq-Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry><mesh filename="package://moying_mcr_description/meshes/sensor/collision/robotiq_ft300.STL"/></geometry>
        </collision>
    </link>
    <link name="${tf_prefix}ft300_mounting_plate">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry><mesh filename="package://moying_mcr_description/meshes/sensor/visual/robotiq_ft300-G-062-COUPLING_G-50-4M6-1D6_20181119.STL"/></geometry>
            <material name="Robotiq-Grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry><mesh filename="package://moying_mcr_description/meshes/sensor/collision/robotiq_ft300-G-062-COUPLING_G-50-4M6-1D6_20181119.STL"/></geometry>
        </collision>
    </link>
    <joint name="${tf_prefix}ft300_mounting_plate" type="fixed">
        <origin xyz="0 0 0.0415" rpy="0 ${pi} 0"/> 
        <parent link="${tf_prefix}ft300_mounting_plate" />
        <child link="${tf_prefix}ft300_sensor" />
    </joint>
    <joint name="${tf_prefix}measurment_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 ${pi} ${-pi/2}" />
        <parent link="${tf_prefix}ft300_sensor" />
        <child link="${tf_prefix}robotiq_ft_frame_id" />
    </joint>
    <link name="${tf_prefix}robotiq_ft_frame_id"/>
  </xacro:macro>

  <xacro:macro name="robotiq_gripper" params="name prefix parent *origin">
    <link name="${prefix}robotiq_85_base_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/robotiq_base.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/robotiq_base.stl" /></geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 2.274e-05 0.03232288" rpy="0 0 0" />
            <mass value="6.6320197e-01" />
            <inertia ixx="5.1617816e-04" iyy="5.8802208e-04" izz="3.9462776e-04" ixy="2.936e-8" ixz="0.0" iyz="-3.2296e-7" />
        </inertial>
    </link>
    <link name="${prefix}robotiq_85_left_knuckle_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/left_knuckle.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/left_knuckle.stl" /></geometry>
        </collision>
        <inertial>
            <origin xyz="0.01213197 0.0002 -0.00058647" rpy="0 0 0" />
            <mass value="1.384773208e-02" />
            <inertia ixx="3.5232e-7" iyy="2.31944e-6" izz="2.23136e-6" ixy="0.0" ixz="1.1744e-7" iyz="0" />
        </inertial>
    </link>
    <link name="${prefix}robotiq_85_right_knuckle_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/right_knuckle.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/right_knuckle.stl" /></geometry>
        </collision>
        <inertial>
            <origin xyz="-0.01213197 0.0002 -0.00058647" rpy="0 0 0" />
            <mass value="1.384773208e-02" />
            <inertia ixx="3.5232e-7" iyy="2.31944e-6" izz="2.23136e-6" ixy="0.0" ixz="-1.1744e-7" iyz="0.0" />
        </inertial>
    </link>
    <link name="${prefix}robotiq_85_left_finger_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/left_finger.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/left_finger.stl" /></geometry>
        </collision>
        <inertial>
            <origin xyz="0.00346899 -0.00079447 0.01867121" rpy="0 0 0" />
            <mass value="4.260376752e-02" />
            <inertia ixx="1.385792000000000e-05" iyy="1.183208e-05" izz="5.19672e-06" ixy="0.0" ixz="-2.17264e-06" iyz="0.0" />
        </inertial>
    </link>
    <link name="${prefix}robotiq_85_right_finger_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/right_finger.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/right_finger.stl" /></geometry>
        </collision>
        <inertial>
            <origin xyz="-0.00346899 -5.53e-06 0.01867121" rpy="0 0 0" />
            <mass value="4.260376752000000e-02" />
            <inertia ixx="1.385792e-05" iyy="1.183208e-05" izz="5.19672e-06" ixy="0.0" ixz="2.17264e-06" iyz="0.0" />
        </inertial>
    </link>
    <link name="${prefix}robotiq_85_left_inner_knuckle_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/left_inner_knuckle.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/left_inner_knuckle.stl" /></geometry>
        </collision>
        <inertial>
            <origin xyz="0.01897699 0.00015001 0.02247101" rpy="0 0 0" />
            <mass value="2.969376448e-02" />
            <inertia ixx="9.57136e-06" iyy="8.69056e-06" izz="8.19144e-06" ixy="0.0" ixz="-3.93424e-06" iyz="0.0" />
        </inertial>
    </link>
    <link name="${prefix}robotiq_85_right_inner_knuckle_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/right_inner_knuckle.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/right_inner_knuckle.stl" /></geometry>
        </collision>
        <inertial>
            <origin xyz="-0.01926824 5.001e-05 0.02222178" rpy="0 0 0" />
            <mass value="2.969376448e-02" />
            <inertia ixx="9.42456e-06" iyy="8.69056e-06" izz="8.33824e-06" ixy="0.0" ixz="3.9636e-06" iyz="0.0" />
        </inertial>
    </link>
    <link name="${prefix}robotiq_85_left_finger_tip_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/left_finger_tip.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/left_finger_tip.stl" /></geometry>
            <surface>
                <friction><ode><mu1>100000.0</mu1><mu2>100000.0</mu2></ode></friction>
                <contact><ode><kp>1e+5</kp><kd>1</kd><soft_cfm>0</soft_cfm><soft_erp>0.2</soft_erp><minDepth>0.002</minDepth><maxVel>0</maxVel></ode></contact>
            </surface>
        </collision>
        <inertial>
            <origin xyz="-0.01456706 -0.0008 0.01649701" rpy="0 0 0" />
            <mass value="4.268588744e-02" />
            <inertia ixx="1.048152e-05" iyy="1.197888e-05" izz="4.22784e-06" ixy="0.0" ixz="3.5232e-6" iyz="0.0" />
        </inertial>
    </link>
    <link name="${prefix}robotiq_85_right_finger_tip_link">
        <visual>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/visual/right_finger_tip.dae" /></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="package://moying_mcr_description/meshes/gripper_85/collision/right_finger_tip.stl" /></geometry>
            <surface>
                <friction><ode><mu1>100000.0</mu1><mu2>100000.0</mu2></ode></friction>
                <contact><ode><kp>1e+5</kp><kd>1</kd><soft_cfm>0</soft_cfm><soft_erp>0.2</soft_erp><minDepth>0.002</minDepth><maxVel>0</maxVel></ode></contact>
            </surface>
        </collision>
        <inertial>
            <origin xyz="0.01456706 5e-05 0.01649701" rpy="0 0 0" />
            <mass value="4.268588744e-02" />
            <inertia ixx="1.048152e-05" iyy="1.197888e-05" izz="4.22784e-06" ixy="0.0" ixz="-3.5232e-06" iyz="0.0" />
        </inertial>
    </link>

    <joint name="${prefix}robotiq_85_base_joint" type="fixed">
        <parent link="${parent}" />
        <child link="${prefix}robotiq_85_base_link" />
        <xacro:insert_block name="origin" />
    </joint>
    <joint name="${prefix}robotiq_85_left_knuckle_joint" type="revolute">
        <parent link="${prefix}robotiq_85_base_link" />
        <child link="${prefix}robotiq_85_left_knuckle_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="0.03060114 0.0 0.05490452" rpy="0 0 0" />
        <limit lower="0.0" upper="0.8" velocity="0.5" effort="50" />
    </joint>
    <joint name="${prefix}robotiq_85_right_knuckle_joint" type="revolute">
        <parent link="${prefix}robotiq_85_base_link" />
        <child link="${prefix}robotiq_85_right_knuckle_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="-0.03060114 0.0 0.05490452" rpy="0 0 0" />
        <limit lower="-0.8" upper="0.0" velocity="0.5" effort="50" />
        <mimic joint="${prefix}robotiq_85_left_knuckle_joint" multiplier="-1" />
    </joint>
    <joint name="${prefix}robotiq_85_left_finger_joint" type="fixed">
        <parent link="${prefix}robotiq_85_left_knuckle_link" />
        <child link="${prefix}robotiq_85_left_finger_link" />
        <origin xyz="0.03152616 0.0 -0.00376347" rpy="0 0 0" />
    </joint>
    <joint name="${prefix}robotiq_85_right_finger_joint" type="fixed">
        <parent link="${prefix}robotiq_85_right_knuckle_link" />
        <child link="${prefix}robotiq_85_right_finger_link" />
        <origin xyz="-0.03152616 0.0 -0.00376347" rpy="0 0 0" />
    </joint>
    <joint name="${prefix}robotiq_85_left_inner_knuckle_joint" type="continuous">
        <parent link="${prefix}robotiq_85_base_link" />
        <child link="${prefix}robotiq_85_left_inner_knuckle_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="0.0127 0.0 0.06142" rpy="0 0 0" />
        <mimic joint="${prefix}robotiq_85_left_knuckle_joint" />
    </joint>
    <joint name="${prefix}robotiq_85_right_inner_knuckle_joint" type="continuous">
        <parent link="${prefix}robotiq_85_base_link" />
        <child link="${prefix}robotiq_85_right_inner_knuckle_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="-0.0127 0.0 0.06142" rpy="0 0 0" />
        <mimic joint="${prefix}robotiq_85_left_knuckle_joint" multiplier="-1" />
    </joint>
    <joint name="${prefix}robotiq_85_left_finger_tip_joint" type="continuous">
        <parent link="${prefix}robotiq_85_left_finger_link" />
        <child link="${prefix}robotiq_85_left_finger_tip_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="0.00563134 0.0 0.04718515" rpy="0 0 0" />
        <mimic joint="${prefix}robotiq_85_left_knuckle_joint" multiplier="-1" />
    </joint>
    <joint name="${prefix}robotiq_85_right_finger_tip_joint" type="continuous">
        <parent link="${prefix}robotiq_85_right_finger_link" />
        <child link="${prefix}robotiq_85_right_finger_tip_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="-0.00563134 0.0 0.04718515" rpy="0 0 0" />
        <mimic joint="${prefix}robotiq_85_left_knuckle_joint" />
    </joint>
  </xacro:macro>

  <xacro:macro name="gazebo_link_setting" params="link_name">
    <gazebo reference="${link_name}">
      <mu1>0.2</mu1><mu2>0.2</mu2><selfCollide>true</selfCollide><gravity>true</gravity>
    </gazebo>
  </xacro:macro>
  <xacro:macro name="prefix_elfin_gazebo_link_setting" params="headprefix prefix">
    <gazebo reference="${headprefix}_elfin_link${prefix}">
      <mu1>0.2</mu1><mu2>0.2</mu2><selfCollide>true</selfCollide><gravity>true</gravity>
    </gazebo>
  </xacro:macro>


  <link name="base_link" />

  <link name="catch_centor"/>
  <joint name="catcha_joint" type="fixed">
    <origin xyz="0.65 0 1.2" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="catch_centor" />
    <dynamics friction="0.1" />
  </joint>

  <link name="mmcomcr"/>
  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="mmcomcr" />
    <dynamics friction="0.1" />
  </joint>

  <xacro:moying_chassis_description mode="${select_mode}"/>

  <xacro:body parent="vehicle_body"/>

  <joint name="extention_shell_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="vehicle_body"/>
    <child link="extention_shell"/>
  </joint>
  <link name="extention_shell">
    <visual>
      <origin rpy="0 0 ${-pi/2}" xyz="0 0 0 "/>
      <geometry><mesh filename="package://moying_mcr_description/meshes/CD6003_TopCover.STL" scale="0.001 0.001 0.001"/></geometry>
      <material name="Silver"/>
    </visual>
    <xacro:if value="${select_mode == 'real'}">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.53"/>
      <geometry><box size="1.05 0.62 0.54"/></geometry>
    </collision>
    </xacro:if>
  </link>

  <xacro:elfin3_description prefix="left_arm" parent="left_arm_base" r="0" p="0" y="0"/>
  <xacro:elfin3_description prefix="right_arm" parent="right_arm_base" r="0" p="0" y="0"/>

  <xacro:if value="${select_mode=='gazebo'}">
    <gazebo>
        <plugin name="ign_ros2_control::IgnitionROS2ControlPlugin" filename="ign_ros2_control-system">
          <robot_param>robot_description</robot_param>
          <robot_param_node>robot_state_publisher</robot_param_node>
          <parameters>${select_settings}</parameters>
          <controller_manager_name>controller_manager</controller_manager_name>         
        </plugin>
    </gazebo>
    <xacro:gazebo_link_setting link_name="chassis_link"/>
    <xacro:gazebo_link_setting link_name="forward_right_wheel"/>
    <xacro:gazebo_link_setting link_name="forward_left_wheel"/>
    <xacro:gazebo_link_setting link_name="back_right_wheel"/>
    <xacro:gazebo_link_setting link_name="back_left_wheel"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="left_arm" prefix="1"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="left_arm" prefix="2"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="left_arm" prefix="3"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="left_arm" prefix="4"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="left_arm" prefix="5"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="left_arm" prefix="6"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="right_arm" prefix="1"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="right_arm" prefix="2"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="right_arm" prefix="3"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="right_arm" prefix="4"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="right_arm" prefix="5"/>
    <xacro:prefix_elfin_gazebo_link_setting headprefix="right_arm" prefix="6"/>
  </xacro:if>

<xacro:if value="${select_mode=='real'}">
    <xacro:robotiq_ft300 parent="left_arm_elfin_dummy_gripper" tf_prefix="left_arm_">
      <origin xyz="0 0 -0.034" rpy="0 0 0"/>
    </xacro:robotiq_ft300>
    <xacro:robotiq_ft300 parent="right_arm_elfin_dummy_gripper" tf_prefix="right_arm_">
      <origin xyz="0 0 -0.034" rpy="0 0 0"/>
    </xacro:robotiq_ft300>
    
    <xacro:robotiq_gripper name="left_gripper" prefix="left_arm_" parent="left_arm_robotiq_ft_frame_id">
      <origin xyz="0 0 0.00" rpy="0 0 0 "/>
    </xacro:robotiq_gripper>
    <xacro:robotiq_gripper name="right_gripper" prefix="right_arm_" parent="right_arm_robotiq_ft_frame_id">
      <origin xyz="0 0 0.00" rpy="0 0 0 "/>
    </xacro:robotiq_gripper>
  </xacro:if>

  <xacro:if value="${select_mode=='mujoco'}">
    <xacro:robotiq_ft300 parent="left_arm_elfin_dummy_gripper" tf_prefix="left_arm_">
      <origin xyz="0 0 -0.034" rpy="0 0 0"/>
    </xacro:robotiq_ft300>
    <xacro:robotiq_ft300 parent="right_arm_elfin_dummy_gripper" tf_prefix="right_arm_">
      <origin xyz="0 0 -0.034" rpy="0 0 0"/>
    </xacro:robotiq_ft300>s
    
    <xacro:robotiq_gripper name="left_gripper" prefix="left_arm_" parent="left_arm_robotiq_ft_frame_id">
      <origin xyz="0 0 0.00" rpy="0 0 0 "/>
    </xacro:robotiq_gripper>
    <xacro:robotiq_gripper name="right_gripper" prefix="right_arm_" parent="right_arm_robotiq_ft_frame_id">
      <origin xyz="0 0 0.00" rpy="0 0 0 "/>
    </xacro:robotiq_gripper>
  </xacro:if>

  <xacro:if value="${select_mode=='gazebo'}">
    <xacro:robotiq_ft300 parent="left_arm_elfin_dummy_gripper" tf_prefix="left_arm_">
      <origin xyz="0 0 -0.034" rpy="0 0 0"/>
    </xacro:robotiq_ft300>
    <xacro:robotiq_ft300 parent="right_arm_elfin_dummy_gripper" tf_prefix="right_arm_">
      <origin xyz="0 0 -0.034" rpy="0 0 0"/>
    </xacro:robotiq_ft300>
    
    <xacro:robotiq_gripper name="left_gripper" prefix="left_arm_" parent="left_arm_robotiq_ft_frame_id">
      <origin xyz="0 0 0.00" rpy="0 0 0 "/>
    </xacro:robotiq_gripper>
    <xacro:robotiq_gripper name="right_gripper" prefix="right_arm_" parent="right_arm_robotiq_ft_frame_id">
      <origin xyz="0 0 0.00" rpy="0 0 0 "/>
    </xacro:robotiq_gripper>
  </xacro:if>

</robot>